import { D, M, L } from "./colors";

// ── Asientos ──────────────────────────────────────────────────────────────────
export function Chair() { return (<><rect x="8" y="4" width="16" height="10" rx="3" fill={L} stroke={D} strokeWidth="1.5"/><rect x="6" y="14" width="20" height="14" rx="3" fill={M} stroke={D} strokeWidth="1.5"/></>); }
export function Bench() { return (<><rect x="3" y="9" width="26" height="8" rx="2" fill={L} stroke={D} strokeWidth="1.5"/><rect x="3" y="17" width="26" height="6" rx="2" fill={M} stroke={D} strokeWidth="1.5"/></>); }
export function SillaTerraza() { return (<><rect x="7" y="3" width="18" height="12" rx="3" fill={L} stroke={D} strokeWidth="1.5"/><rect x="5" y="15" width="22" height="13" rx="3" fill={M} stroke={D} strokeWidth="1.5"/><rect x="3" y="17" width="4" height="9" rx="2" fill={D} opacity="0.5"/><rect x="25" y="17" width="4" height="9" rx="2" fill={D} opacity="0.5"/></>); }
export function Tumbona() { return (<><rect x="2" y="10" width="22" height="12" rx="3" fill={M} stroke={D} strokeWidth="1.5"/><rect x="24" y="8" width="6" height="16" rx="3" fill={L} stroke={D} strokeWidth="1.5"/><rect x="4" y="22" width="4" height="4" rx="1" fill={D} opacity="0.4"/><rect x="16" y="22" width="4" height="4" rx="1" fill={D} opacity="0.4"/></>); }
export function CamaBalinesa() { return (<><rect x="4" y="6" width="24" height="20" rx="2" fill={L} stroke={D} strokeWidth="1.5"/><rect x="4" y="6" width="24" height="5" rx="1" fill={M}/><circle cx="4" cy="6" r="2" fill={D} opacity="0.6"/><circle cx="28" cy="6" r="2" fill={D} opacity="0.6"/><circle cx="4" cy="26" r="2" fill={D} opacity="0.6"/><circle cx="28" cy="26" r="2" fill={D} opacity="0.6"/></>); }
export function Hamaca() { return (<><rect x="2" y="13" width="4" height="10" rx="2" fill={D} opacity="0.6"/><rect x="26" y="13" width="4" height="10" rx="2" fill={D} opacity="0.6"/><path d="M6 15 Q16 22 26 15" stroke={D} strokeWidth="2.5" fill={L} strokeLinecap="round"/><path d="M6 19 Q16 26 26 19" stroke={D} strokeWidth="1.5" fill="none" strokeLinecap="round" opacity="0.4"/></>); }
export function Pouf() { return (<><circle cx="16" cy="16" r="11" fill={M} stroke={D} strokeWidth="1.5"/><circle cx="16" cy="16" r="6" fill={L} stroke={D} strokeWidth="1" strokeDasharray="3 2"/></>); }
export function Taburete() { return (<><circle cx="16" cy="13" r="8" fill={M} stroke={D} strokeWidth="1.5"/><line x1="10" y1="21" x2="8" y2="29" stroke={D} strokeWidth="2" strokeLinecap="round"/><line x1="22" y1="21" x2="24" y2="29" stroke={D} strokeWidth="2" strokeLinecap="round"/><line x1="16" y1="21" x2="16" y2="29" stroke={D} strokeWidth="2" strokeLinecap="round"/></>); }

// ── Muebles extra ─────────────────────────────────────────────────────────────
export function Sillon() { return (<><rect x="8" y="5" width="16" height="10" rx="3" fill={L} stroke={D} strokeWidth="1.5"/><rect x="6" y="15" width="20" height="13" rx="3" fill={M} stroke={D} strokeWidth="1.5"/><rect x="3" y="15" width="5" height="10" rx="2" fill={D} opacity="0.45"/><rect x="24" y="15" width="5" height="10" rx="2" fill={D} opacity="0.45"/></>); }
export function Otomana() { return (<><rect x="4" y="8" width="24" height="16" rx="8" fill={M} stroke={D} strokeWidth="1.5"/><rect x="8" y="12" width="16" height="8" rx="4" fill={L} stroke={D} strokeWidth="1" opacity="0.6"/></>); }
export function MesaOval() { return (<><ellipse cx="16" cy="16" rx="13" ry="8" fill={L} stroke={D} strokeWidth="1.5"/><ellipse cx="16" cy="16" rx="8" ry="4" fill={M} stroke={D} strokeWidth="1" opacity="0.55"/></>); }
export function MesaCock() { return (<><circle cx="16" cy="16" r="9" fill={L} stroke={D} strokeWidth="1.5"/><circle cx="16" cy="16" r="4" fill={M}/></>); }
export function MesaNovios() { return (<><rect x="2" y="9" width="28" height="14" rx="2" fill={M} stroke={D} strokeWidth="2"/><path d="M12 16 Q16 11 20 16" stroke="white" strokeWidth="1.5" fill="none" strokeLinecap="round"/><circle cx="9" cy="16" r="2" fill="white" opacity="0.5"/><circle cx="23" cy="16" r="2" fill="white" opacity="0.5"/></>); }
